### ISSUE TITLE
Releases are a bit hard to find due to incorrect links

### ISSUE THREAD

**Issue by wolph** [ambilight-4-mediaportal/AtmoLight#2]
- releases list of this repo only has 1 release from 2014: https://github.com/ambilight-4-mediaportal/AtmoLight/releases
- Download archive in the readme only has old releases: https://ambilight-4-mediaportal.googlecode.com/git/MPEI%20Release/Atmolight/
- Google code link is still in the readme but everything over there is obsolete: https://code.google.com/p/ambilight-4-mediaportal/
- Mediaportal atmolight plugin is a year old: http://www.team-mediaportal.com/extensions/other/atmolight-plugin-for-atmowin

These links should either be removed or updated with a new version. But a big fat download button at the top of the readme could help :)

**Comment by Lightning303** [comment]
Thanks,
with googlecode shutting down we moved the files, however it seems we did not update all the refrences to it. In general, MPE will always have the up to date versions, and you can find all the latest news on the forum. http://forum.team-mediaportal.com/threads/atmolight-1-17-0-0-2015-10-19.125633/

**Comment by RickDB** [comment]
[MediaPortal Extension Manager (MPEM)](http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/17_Extensions/1_Installer_%28MPEI%29) will always have the latest releases as with all the other plugins which is what is recommend because of automatic updates and security as well, manual installations is really for those who want to tinker with beta releases and such :)

@Lightning303 Will check the documentation and links as well and see if we missed some more linking to google code and such.

**Comment by RickDB** [comment]
@Lightning303 Updated wiki pages and have one thing left here:

http://www.team-mediaportal.com/extensions/other/atmolight-plugin-for-atmowin

The external changelog links to google code which should be this one for MP1:

https://github.com/ambilight-4-mediaportal/AtmoLight/blob/master/AtmoLight.MediaPortal1/changelog.txt

other than that looks alright now.

**Comment by wolph** [comment]
Great, thanks for the update :)
